# Generated by Django 6.0.2 on 2026-02-08 00:33

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cropitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rate', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cropitem',
                'verbose_name_plural': 'Cropitem',
            },
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=40, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='signatures', validators=[app.models.validate_image_size])),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CustomerInfo',
                'verbose_name_plural': 'CustomerInfo',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tomatoes', models.IntegerField(default=0)),
                ('bell_pepper', models.IntegerField(default=0)),
                ('cucumber', models.IntegerField(default=0)),
                ('abernero', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('invoice_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateField(blank=True, null=True, validators=[app.models.validate_not_future])),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customerinfo')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoice',
            },
        ),
    ]
