# Generated by Django 6.0.2 on 2026-02-09 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='name',
            new_name='customer_id',
        ),
    ]
